### PR TITLE
Add DEBUG config flag

### PR DESCRIPTION
**Pull request by eengstrom**
add to config.json; used to avoid actually send cards
updated config.json example to document all the options, including new DEBUG option

### CODE REVIEW

**Comment by tomreece** [comment]
I like the addition of the debug key, but don't like the comments that you have to remove in the JSON. How about we make some note keys? Like `"hours_to_run_description": "Kills the bot after it has been running for some number of hours. This counteracts Firefox/Selenium memory leaks. Use startup.py to launch Pucauto to auto restart. Good for low resource servers."`

**Comment by eengstrom** [comment]
Understood.  So how about we just take the change to pucauto.py and ignore the config file example for now.  See my latest suggestion in #52.

**Comment by tomreece** [comment]
I like that idea. I'm fine with merging if you remove the `config.example.json` changes for now and we solve that in a different way.

The debug flag is useful and can be made use of in pucauto.py like you have, even if no one else knows it exists yet.

**Comment by eengstrom** [comment]
Done.  just the change to introduce first use of the DEBUG flag is in `pucauto.py`

**Comment by tomreece** [comment]
Looks good. Thanks for the compromise. I love your idea of getting comments in the config file, I was just afraid for new users. They have enough trouble editing config.json anyway because their editors are turning normal quotes into smart quotes. I get that email so frequently haha.

**Comment by tomreece** [comment]
@eengstrom what if I just used something like this for JSON comments: https://commentjson.readthedocs.org/en/latest/

It lets you write:

```
{
    "name": "Vaidik Kapoor", # Person's name
    "location": "Delhi, India", // Person's location

    # Section contains info about
    // person's appearance
    "appearance": {
        "hair_color": "black",
        "eyes_color": "black",
        "height": "6"
    }
}
```

**Comment by eengstrom** [comment]
See comments in issue #65

**Pull request merged**
