### PR TITLE
Ability to run in both Python 2 and 3

### LINKED ISSUE #16: Crash in filter_trades_dict()
```
E:\GitHub\pucauto> python pucauto.py

     _______  __   __  _______  _______  __   __  _______  _______
    |       ||  | |  ||       ||   _   ||  | |  ||       ||       |
    |    _  ||  | |  ||       ||  |_|  ||  | |  ||_     _||   _   |
    |   |_| ||  |_|  ||       ||       ||  |_|  |  |   |  |  | |  |
    |    ___||       ||      _||       ||       |  |   |  |  |_|  |
    |   |    |       ||     |_ |   _   ||       |  |   |  |       |
    |___|    |_______||_______||__| |__||_______|  |___|  |_______|
    www.pucauto.com                                          v0.3.0


Logging in...
Turning on auto matching...
Sorting by member...
Finding trades...
Traceback (most recent call last):
  File "pucauto.py", line 239, in <module>
    main()
  File "pucauto.py", line 236, in main
    find_trades()
  File "pucauto.py", line 216, in find_trades
    valid_trades = filter_trades_dict(trades)
  File "pucauto.py", line 177, in filter_trades_dict
    for member, v in trades.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
```

### PR DESCRIPTION
**Pull request by XVicarious**
Check for version.  If 2, use iteritems.  Otherwise use items.

Resolves #16

### CODE REVIEW

**Comment by tomreece** [comment]
@XVicarious Can you resolve the conflicts.

**Comment by XVicarious** [comment]
Should be all good now.

**Comment by tomreece** [comment]
@XVicarious Would you care to implement this using Six instead? https://pythonhosted.org/six/ This will help support both Python 2 and 3 down the line incase other functionality needs to be used.

**Comment by XVicarious** [comment]
Sure thing.  I'll work on it when I get home from work.

**Comment by tomreece** [comment]
Thanks a lot for your contribution man!

**Comment by XVicarious** [comment]
Okay, tested using Python 3.   No crashes parsing trades and the like.

**Comment by tomreece** [comment]
So much cleaner, now just need to add six to the `requirements.txt` file.

**Comment by tomreece** [comment]
Is there an easy way for me to contribute to your fork other than adding you as a remote and pushing code to you without your permission? I want to make these minor changes without bothering you.

**Comment by XVicarious** [comment]
I added you to my fork's collaborators

**Comment by XVicarious** [comment]
I have officially added six to requirements.txt.

**Comment by tomreece** [comment]
Thanks for your contribution!

**Pull request merged**
