### PR TITLE
Fix #84

### LINKED ISSUE #82: Bundle Pucauto up as something users can just double click to start without the setup
Installing Python an dependencies and stuff is more complicated than a majority of people are accustomed to. Surely I can make this easier for folks.

### LINKED ISSUE #84: Pucauto Commits to Send Copies You Don't Have
There isn't much I can do to prove or show this happening (as it always happens while I'm away or not looking), but Pucauto will commit to send multiple copies of cards I don't have.

For example last week it commit to send someone two copies of the new Olivia to someone even though my haves list only had one copy on it.  The same thing happened with a copy of Shard Volley.

The output tells me it found x trades to someone with y points and then shows the card on the list twice.

### PR DESCRIPTION
**Pull request by XVicarious**
This should fix issue 84

### CODE REVIEW

**Comment by XVicarious** [comment]
Okay, it doesn't seem to be working right.  I'm figuring it out now.

**Comment by XVicarious** [comment]
Okay, it was a really stupid mistake.  I however am having issues with encoding and it printing out sent trades.  Can someone confirm?

Edit:  Line 344.

**Comment by drakeblood4** [comment]
Hey, I found another source of puca double commits. When scrolling, Puca will occasionally load additional copies of a card you don't have enough of from a user right along the scroll border. I haven't found any way to fix this without using the export feature available to Uncommon users, but I figured this might be useful.

**Comment by XVicarious** [comment]
drakeblood4, do you know if the copies have the same ID?

**Comment by tomreece** [comment]
@XVicarious I don't understand how a duplicate trade ID would result in two copies of a card being sent to a user. For example, if you send https://pucatrade.com/trades/sendcard/14787307, and then tried to send it again, wouldn't PucaTrade come back with "Sorry someone beat you to it" or something along those lines because that ID has already been traded?

**Comment by tomreece** [comment]
I think the problem is on PucaTrades end as @drakeblood4 mentions. If a sender has 1 copy of Snapcaster on their Haves list and a receiver wants 2 copies, then PucaTrade's Send Card page should only show the sender 1 row for that receiver, but I think sometimes as the page is loading (via AJAX) in some cases a second row for that same receiver makes its way onto the list even though the sender only has 1 copy. Then Pucauto commits to send both and PucaTrade has no checking to see if you even have the card on your haves list. This is probably part of the problem. PucaTrade's logic should probably require me to have a card on my haves list in order to send it to someone.

**Pull request closed without merging**
